package com.qingfeng.music.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MUSIC".
 */
@Entity
public class Music {

    @Id
    private Long id;
    private String title;
    private String album;
    private Long albumId;
    private String artist;
    private String path;
    private String displayName;
    private Integer duration;
    private Integer size;
    private Integer collect;
    private Long lrcId;
    private String lrcUrl;
    private String imageUrl;
    private String encode;
    private String decode;
    public String getDecode() {
        return this.decode;
    }
    public void setDecode(String decode) {
        this.decode = decode;
    }
    public String getEncode() {
        return this.encode;
    }
    public void setEncode(String encode) {
        this.encode = encode;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public String getLrcUrl() {
        return this.lrcUrl;
    }
    public void setLrcUrl(String lrcUrl) {
        this.lrcUrl = lrcUrl;
    }
    public Long getLrcId() {
        return this.lrcId;
    }
    public void setLrcId(Long lrcId) {
        this.lrcId = lrcId;
    }
    public Integer getCollect() {
        return this.collect;
    }
    public void setCollect(Integer collect) {
        this.collect = collect;
    }
    public Integer getSize() {
        return this.size;
    }
    public void setSize(Integer size) {
        this.size = size;
    }
    public Integer getDuration() {
        return this.duration;
    }
    public void setDuration(Integer duration) {
        this.duration = duration;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getPath() {
        return this.path;
    }
    public void setPath(String path) {
        this.path = path;
    }
    public String getArtist() {
        return this.artist;
    }
    public void setArtist(String artist) {
        this.artist = artist;
    }
    public Long getAlbumId() {
        return this.albumId;
    }
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }
    public String getAlbum() {
        return this.album;
    }
    public void setAlbum(String album) {
        this.album = album;
    }
    public String getTitle() {
        return this.title;
    }
    public void setTitle(String title) {
        this.title = title;
    }
    public Long getId() {
        return this.id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    @Generated(hash = 322010889)
    public Music(Long id, String title, String album, Long albumId, String artist, String path,
            String displayName, Integer duration, Integer size, Integer collect, Long lrcId,
            String lrcUrl, String imageUrl, String encode, String decode) {
        this.id = id;
        this.title = title;
        this.album = album;
        this.albumId = albumId;
        this.artist = artist;
        this.path = path;
        this.displayName = displayName;
        this.duration = duration;
        this.size = size;
        this.collect = collect;
        this.lrcId = lrcId;
        this.lrcUrl = lrcUrl;
        this.imageUrl = imageUrl;
        this.encode = encode;
        this.decode = decode;
    }
    @Generated(hash = 1263212761)
    public Music() {
    }



}
